<form action="add_project.php" method="post" enctype="multipart/form-data">
<fieldset>
<legend>Ajouter un projet</legend>
    <ul>
        <li>
            <label for="title_project">Nom du projet:</label>
            <input name="title_project" type="text">
        </li>
        <li>
            <label for="url_project">url:</label>
            <input name="url_project" type="text">
        </li>
        <li>
            <label for="photo_project">Image de présentation</label>
            <input name="photo_project" type="file">
        </li>
    </ul>
</fieldset>
<button type="submit">envoyer</button>
</form>