
<div class="background">
    
                
        <h1 class="title_main title_name"><span class="name">Fabien</span> <span class="name">ESTRABAUD</span></h1>
        
        <h1 class="title_main title_about_me"><span class="name">A propos</span></h1>



        
        <div class="about_title">
        <h2 class="title_little">Développeur & Intégrateur d'applications web</h2>
        </div>


    <section class="about">
        <article>
            <h2>Qu'est ce qu'un developpeur?</h2>
            <p>Chargé de la réalisation d'un site internet et des fonctionnalités qui vont avec, le développeur web est un programmateur multi-tâches et multi-languages, très flexible (agile), afin de s'adapter aux nombreux besoins d'un site internet.</p>
        </article>
        <article>
            <h2>Lorem ipsum dolor sit.</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum veritatis voluptate omnis laborum facere earum pariatur saepe suscipit neque quod, iure obcaecati distinctio harum magnam consequatur quam autem. Ea sequi pariatur nihil reiciendis culpa inventore delectus maxime sapiente? A rerum voluptatum dolorum tenetur possimus natus fuga quas? Impedit, nemo. Explicabo omnis mollitia delectus unde! Consequuntur, obcaecati? Doloribus dolore necessitatibus placeat suscipit. Perferendis sit necessitatibus optio quia nihil amet sapiente distinctio ut neque non deleniti tempore corrupti laborum, eum, tenetur ratione atque officia obcaecati qui? Distinctio earum quo neque quia ullam nam, mollitia deserunt, accusamus sed pariatur voluptates minima facilis porro?</p>
        </article>
        <article>
            <h2>Lorem ipsum dolor sit amet.</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nostrum quas enim quam assumenda, dolore omnis laborum suscipit! Rem, suscipit expedita! Similique illo sapiente amet commodi, rerum optio ad nulla cum accusamus repudiandae saepe alias. Aut optio aperiam nam quidem ut quo in ducimus pariatur odio repellat eius nemo explicabo quas consequatur consectetur at animi dicta asperiores praesentium adipisci officia, inventore cupiditate possimus. Quibusdam quo magnam iusto fugit voluptas, adipisci eius nostrum itaque repellat saepe deleniti nam blanditiis minima, illum at?</p>
        </article>
    </section>
</div>
<!-- <div class="gradient">

</div> -->
<div class="background_formation">
    <section id="formation" class="about_formation">
    <div class="filter">
        <div class="container">
            <h1 class="title_formation">Formations</h1>
            <div class="item">
                <div class="image">
                    <div>
                    <img src="http://lorempixel.com/400/400/people/1/" />
                    <span>
                    09.12.2016
                    </span>
                    </div>
                </div>
                <div class="details">
                    <div>
                    <h2>Phasellus pharetra</h2>
                    <p>Proin condimentum tempus ultrices. Suspendisse vestibulum suscipit erat, ac efficitur lorem. Nullam non ex vel turpis imperdiet maximus sit amet nec odio. Donec mauris nisl, vestibulum id efficitur at, convallis id dui. Sed enim nisl, ultrices vitae sodales eu, vestibulum a mi. Morbi consectetur pulvinar sagittis. Phasellus pharetra diam id leo gravida pharetra. In rutrum est gravida, maximus mi ac, mattis metus. Ut at tempus sem. Vivamus condimentum erat eget aliquet dignissim. </p>
                    </div>
                </div>
                </div>

                <div class="item">
                <div class="image">
                    <div>
                    <img src="http://lorempixel.com/400/400/people/3/" />
                    <span>
                    08.12.2016
                    </span>
                    </div>
                </div>
                <div class="details">
                    <div>
                    <h2>Proin consectetur</h2>
                    <p>Quisque vestibulum iaculis felis eget varius. Morbi bibendum lectus felis, sed vehicula purus pellentesque eu. Maecenas sit amet libero vel nunc porta tincidunt fringilla nec mauris. Phasellus pharetra pharetra massa. Ut maximus purus eget libero dapibus, sit amet ultricies eros auctor. Nulla tristique dui nec libero rhoncus, et dictum odio lobortis. Proin consectetur nec sapien hendrerit lobortis. Proin mi odio, mollis ac ullamcorper in, pellentesque non nulla. In pretium purus at posuere efficitur. Donec eget cursus quam, in mollis libero. Mauris tempor volutpat sodales. Nulla in odio nec metus elementum ultricies sit amet vel dolor. Nunc non ligula at libero eleifend consectetur nec eu felis. Sed tristique vel ante eu pulvinar. Pellentesque elementum congue iaculis. Integer lorem sapien, vestibulum sed semper sed, dictum nec purus. Aenean porttitor interdum iaculis. </p>
                    </div>
                </div>
                </div>

                <div class="item">
                <div class="image">
                    <div>
                    <img src="http://lorempixel.com/400/400/people/8/" />
                    <span>
                    07.12.2016
                    </span>
                    </div>
                </div>
                <div class="details">
                    <div>
                    <h2>Duis porta urna</h2>
                    <p>In nulla mi, ultrices et ullamcorper molestie, rhoncus at purus. Nulla et metus elementum, molestie lectus eget, pretium sapien. Duis dapibus libero id vehicula sodales. Curabitur augue tellus, lacinia ac turpis sit amet, facilisis finibus mauris. Mauris laoreet neque nisi, id hendrerit diam cursus ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Duis porta urna ligula, nec consequat libero congue quis. Nulla convallis enim sed dolor viverra, eget dapibus lorem ultricies. Nullam et neque vitae nulla faucibus sollicitudin eget sit amet justo.</p>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </section>
</div>

