
<div class="background">
    
                
        <h1 class="title_main title_name"><span class="name">Fabien</span> <span class="name">ESTRABAUD</span></h1>
        
        <h1 class="title_main title_about_me"><span class="name">A propos</span></h1>



        
        <div class="about_title">
        <h2 class="title_little">Développeur & Intégrateur d'applications web</h2>
        </div>


    <section class="about">
        <article>
            <h2>Qu'est ce qu'un developpeur?</h2>
            <p>Chargé de la réalisation d'un site internet et des fonctionnalités qui vont avec, le développeur web est un programmateur multi-tâches et multi-languages, très flexible (agile), afin de s'adapter aux nombreux besoins d'un site internet.</p>
        </article>
        <article>
            <h2>Lorem ipsum dolor sit.</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum veritatis voluptate omnis laborum facere earum pariatur saepe suscipit neque quod, iure obcaecati distinctio harum magnam consequatur quam autem. Ea sequi pariatur nihil reiciendis culpa inventore delectus maxime sapiente? A rerum voluptatum dolorum tenetur possimus natus fuga quas? Impedit, nemo. Explicabo omnis mollitia delectus unde! Consequuntur, obcaecati? Doloribus dolore necessitatibus placeat suscipit. Perferendis sit necessitatibus optio quia nihil amet sapiente distinctio ut neque non deleniti tempore corrupti laborum, eum, tenetur ratione atque officia obcaecati qui? Distinctio earum quo neque quia ullam nam, mollitia deserunt, accusamus sed pariatur voluptates minima facilis porro?</p>
        </article>
        <article>
            <h2>Lorem ipsum dolor sit amet.</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nostrum quas enim quam assumenda, dolore omnis laborum suscipit! Rem, suscipit expedita! Similique illo sapiente amet commodi, rerum optio ad nulla cum accusamus repudiandae saepe alias. Aut optio aperiam nam quidem ut quo in ducimus pariatur odio repellat eius nemo explicabo quas consequatur consectetur at animi dicta asperiores praesentium adipisci officia, inventore cupiditate possimus. Quibusdam quo magnam iusto fugit voluptas, adipisci eius nostrum itaque repellat saepe deleniti nam blanditiis minima, illum at?</p>
        </article>
    </section>
</div>

<div class="background_formation">
<div class="filter">
    <section id="formation" class="about_formation">
    
        <div class="container">
            <h1 class="title_formation">Formations</h1>
            <div class="item">
                <div class="image pixel">
                    <div>
                    <img src="img/3wa.png" />
                    <span>
                    2018
                    </span>
                    </div>
                </div>
                <div class="details">
                    <div>
                    <h2>Developpeur intégrateur en réalisation
                    d’applications web </h2>
                    <h3>3WA - Paris 18</h3>
                    <p>Titre RNCP niveau III (équivalent bac +2)     </p>
                    </div>
                </div>
                </div>

                <div class="item">
                <div class="image">
                    <div>
                    <img src="img/LOGO-IDRAC-2.jpg" />
                    <span>
                   2010
                    </span>
                    </div>
                </div>
                <div class="details">
                    <div>
                    <h2>Master M.G.E  </h2>
                    <h3>IDRAC Ecole Supérieure de Commerce - Paris 17</h3>
                    <p>MASTER Marketing et Gestion des Entreprises</p>
                    </div>
                </div>
                </div>

                <div class="item">
                <div class="image">
                    <div>
                    <img src="img/LOGO-IDRAC-2.jpg" />
                    <span>
                    2008
                    </span>
                    </div>
                </div>
                <div class="details">
                    <div>
                    <h2>BTS M.U.C</h2>
                    <h3>IDRAC Ecole Supérieure de Commerce - Paris 17</h3>
                    <p>B.T.S Management des Unités Commerciales</p>
                    </div>
                </div>
            </div>
        </div>
    
    </section>
</div>
</div>

<div class="background_competence">
    <div class="container">
        <section class="competence">
            <h1>Mes compétences à votre services</h1>

            <div class="web_logo_container">
                <ul>
                    <li><img src="img/competences/HTML.png" alt=""></li>
                    <li><img src="img/competences/CSS.jpeg" alt="" ></li>
                    <li><img src="img/competences/JS.jpeg" alt="" ></li>
                    <li><img src="img/competences/Jquery.png" alt="" ></li>
                    <li><img src="img/competences/Bootstrap.png" alt="" ></li>
                    <li><img src="img/competences/PHP.jpeg" alt="" ></li>
                    <li><img src="img/competences/MySql.png" alt="" ></li>
                    <li><img src="img/competences/wordpress.jpeg" alt="" ></li>
                </ul>

            </div>
        </section>
    </div>
</div>
        <section class="project">
            <h1>Mes divers projets réalisés</h1>
            <?php if(array_key_exists('firstName',$_SESSION)==true): ?>
                <button><a href="add_project.php">Ajouter un projet</a></button>
            <?php endif ?>
        </section>


