

<div class="container">
            
<h1 class="title_main title_name"><span class="name">Fabien</span> <span class="name">ESTRABAUD</span></h1>
<h1 class="title_main title_competence"><span class="name">Compétences</span></h1>
<h1 class="title_main title_formation"><span class="name">Formations</span></h1>
<h1 class="title_main title_project"><span class="name">Projets</span></h1>



        
    <div class="about_title">
        <h2 class="title_little">Développeur & Intégrateur d'applications web</h2>
    </div>
    <section class="about">
        <article>
            <h2>Lorem ipsum dolor sit amet consectetur.</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione ducimus rem illo nemo aspernatur quam itaque modi qui enim illum laboriosam vitae doloribus eveniet, aliquam assumenda temporibus fugiat, placeat repudiandae dolorum. Inventore, nobis! Temporibus vitae id nihil ex reprehenderit optio placeat voluptatibus dolore nostrum, at ipsa rerum earum, quod porro!</p>
        </article>
        <article>
            <h2>Lorem ipsum dolor sit.</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum veritatis voluptate omnis laborum facere earum pariatur saepe suscipit neque quod, iure obcaecati distinctio harum magnam consequatur quam autem. Ea sequi pariatur nihil reiciendis culpa inventore delectus maxime sapiente? A rerum voluptatum dolorum tenetur possimus natus fuga quas? Impedit, nemo. Explicabo omnis mollitia delectus unde! Consequuntur, obcaecati? Doloribus dolore necessitatibus placeat suscipit. Perferendis sit necessitatibus optio quia nihil amet sapiente distinctio ut neque non deleniti tempore corrupti laborum, eum, tenetur ratione atque officia obcaecati qui? Distinctio earum quo neque quia ullam nam, mollitia deserunt, accusamus sed pariatur voluptates minima facilis porro?</p>
        </article>
        <article>
            <h2>Lorem ipsum dolor sit amet.</h2>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Nostrum quas enim quam assumenda, dolore omnis laborum suscipit! Rem, suscipit expedita! Similique illo sapiente amet commodi, rerum optio ad nulla cum accusamus repudiandae saepe alias. Aut optio aperiam nam quidem ut quo in ducimus pariatur odio repellat eius nemo explicabo quas consequatur consectetur at animi dicta asperiores praesentium adipisci officia, inventore cupiditate possimus. Quibusdam quo magnam iusto fugit voluptas, adipisci eius nostrum itaque repellat saepe deleniti nam blanditiis minima, illum at?</p>
        </article>
    </section>

    <section id="formation" class="about_formation">
        <article class="date">

        </article>

    </section>
</div>