




<form class='login_form' action="login.php" method="post">
    <fieldset>
        <legend>Informations de connexions</legend>
        <ul>
            <li>
                <label for="email">Votre adresse mail: </label>
                <input name="email" type="text">
            </li>
            <li>
                <label for="psw">Votre mot de passe: </label>
                <input name="psw" type="text">
            </li>
        </ul>
                <button type="submit">Se connecter</button>
    </fieldset>
</form>